version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: scraper
    main: ./cmd/scraper
    binary: scraper
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - formats: [tar.gz]

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"
